function [Ne, dNe]=buildnlin_der(xi,eta,zeta)
dNe=1/8*[-(1-eta).*(1-zeta),(1-eta).*(1-zeta),(1+eta).*(1-zeta),...
    -(1+eta).*(1-zeta),-(1-eta).*(1+zeta),(1-eta).*(1+zeta),...
    (1+eta).*(1+zeta),-(1+eta).*(1+zeta);-(1-xi).*(1-zeta),-(1+xi).*(1-zeta),(1+xi).*(1-zeta),...
    (1-xi).*(1-zeta),-(1-xi).*(1+zeta),-(1+xi).*(1+zeta),...
    (1+xi).*(1+zeta),(1-xi).*(1+zeta);-(1-xi).*(1-eta),-(1+xi).*(1-eta),-(1+xi).*(1+eta),...
    -(1-xi).*(1+eta),(1-xi).*(1-eta),(1+xi).*(1-eta),...
    (1+xi).*(1+eta),(1-xi).*(1+eta)];
Ne=1/8*[(1-xi).*(1-eta).*(1-zeta),(1+xi).*(1-eta).*(1-zeta),(1+xi).*(1+eta).*(1-zeta),...
    (1-xi).*(1+eta).*(1-zeta),(1-xi).*(1-eta).*(1+zeta),(1+xi).*(1-eta).*(1+zeta),...
    (1+xi).*(1+eta).*(1+zeta),(1-xi).*(1+eta).*(1+zeta)];
end